QUESTION :3
1. Create Bag-of-Words representation of text data. (5 Marks)
2. Generate TF-IDF matrix using sklearn. (5 Marks)
3. Compare BoW and TF-IDF outputs. (5 Marks)
4. Calculate cosine similarity between two documents. (5 Marks)
5. Demonstrate semantic similarity using word vectors. (5 Marks)
6. Build a mini text processing pipeline combining all steps. (5 Marks)

In [ ]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity


Distance formulae = d(p,q) = (&(pi - qi)^2)^square root

E = summation

&  ==> (E^n i = 1)

similarity=Cos(0) =A*B/|A||B|

In [4]:
documents = [
    "I love machine learning",
    "Machine learning is amazing",
    "I love deep learning",
    "Deep learning drives AI"
]

In [6]:
#create a bag of words represenatation of text data..
vectorizer = CountVectorizer()
bow_matrix = vectorizer.fit_transform(documents)

print("Vocabulary:", vectorizer.get_feature_names_out())
print("BoW Matrix:\n", bow_matrix.toarray())

Vocabulary: ['ai' 'amazing' 'deep' 'drives' 'is' 'learning' 'love' 'machine']
BoW Matrix:
 [[0 0 0 0 0 1 1 1]
 [0 1 0 0 1 1 0 1]
 [0 0 1 0 0 1 1 0]
 [1 0 1 1 0 1 0 0]]


In [7]:
# Generate TF-IDF matrix using sklearn
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(documents)

print("TF-IDF Matrix:\n", tfidf_matrix.toarray())

TF-IDF Matrix:
 [[0.         0.         0.         0.         0.         0.42389674
  0.64043405 0.64043405]
 [0.         0.58783765 0.         0.         0.58783765 0.30675807
  0.         0.46345796]
 [0.         0.         0.64043405 0.         0.         0.42389674
  0.64043405 0.        ]
 [0.58783765 0.         0.46345796 0.58783765 0.         0.30675807
  0.         0.        ]]


In [8]:
#compare BoW-TF_IDF outputs
bow_df = pd.DataFrame(bow_matrix.toarray(), columns=vectorizer.get_feature_names_out())
tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=tfidf_vectorizer.get_feature_names_out())

print("BoW:\n", bow_df)
print("\nTF-IDF:\n", tfidf_df)

BoW:
    ai  amazing  deep  drives  is  learning  love  machine
0   0        0     0       0   0         1     1        1
1   0        1     0       0   1         1     0        1
2   0        0     1       0   0         1     1        0
3   1        0     1       1   0         1     0        0

TF-IDF:
          ai   amazing      deep    drives        is  learning      love  \
0  0.000000  0.000000  0.000000  0.000000  0.000000  0.423897  0.640434   
1  0.000000  0.587838  0.000000  0.000000  0.587838  0.306758  0.000000   
2  0.000000  0.000000  0.640434  0.000000  0.000000  0.423897  0.640434   
3  0.587838  0.000000  0.463458  0.587838  0.000000  0.306758  0.000000   

    machine  
0  0.640434  
1  0.463458  
2  0.000000  
3  0.000000  


In [10]:
#calculate cosine similarity between two documents 
cos_sim = cosine_similarity(tfidf_matrix[0], tfidf_matrix[1])
print("Cosine Similarity:", cos_sim[0][0])

Cosine Similarity: 0.4268480040356374


In [11]:
#Demonstrating semantic and similarity using word vector 
doc1 = ["machine learning is powerful"]
doc2 = ["AI and machine learning are closely related"]

tfidf = TfidfVectorizer()
vectors = tfidf.fit_transform(doc1 + doc2)

similarity = cosine_similarity(vectors[0], vectors[1])

print("Semantic Similarity:", similarity[0][0])

Semantic Similarity: 0.23790309463326234


In [12]:
#Build a mini text processing pipeline combining all steps.
def text_pipeline(docs):
    bow = CountVectorizer()
    bow_matrix = bow.fit_transform(docs)
    tfidf = TfidfVectorizer()
    tfidf_matrix = tfidf.fit_transform(docs)
    similarity = cosine_similarity(tfidf_matrix)
    return {
        "BoW": bow_matrix.toarray(),
        "TF-IDF": tfidf_matrix.toarray(),
        "Similarity": similarity
    }

results = text_pipeline(documents)

print("BoW:\n", results["BoW"])
print("\nTF-IDF:\n", results["TF-IDF"])
print("\nSimilarity:\n", results["Similarity"])

BoW:
 [[0 0 0 0 0 1 1 1]
 [0 1 0 0 1 1 0 1]
 [0 0 1 0 0 1 1 0]
 [1 0 1 1 0 1 0 0]]

TF-IDF:
 [[0.         0.         0.         0.         0.         0.42389674
  0.64043405 0.64043405]
 [0.         0.58783765 0.         0.         0.58783765 0.30675807
  0.         0.46345796]
 [0.         0.         0.64043405 0.         0.         0.42389674
  0.64043405 0.        ]
 [0.58783765 0.         0.46345796 0.58783765 0.         0.30675807
  0.         0.        ]]

Similarity:
 [[1.         0.426848   0.58984422 0.13003375]
 [0.426848   1.         0.13003375 0.09410051]
 [0.58984422 0.13003375 1.         0.426848  ]
 [0.13003375 0.09410051 0.426848   1.        ]]
